#!/bin/bash

[ "$UID" -ne "0" ] && { echo "This script must be run as the root user"; exit 1; }

for FILENAME in $@; do
	DEVICE=`grep " $(stat --print='%m' $FILENAME) " /proc/mounts |awk '{ print $1 }'`
	if [ "$DEVICE" = "/dev/root" ]; then
		DEVNO="$(mountpoint -d /)"
		for DEV in $(stat --printf='%t:%T:%n ' /dev/sd*); do
			echo "$DEV" |grep "^$DEVNO" >/dev/null &&
				DEVICE=$(echo "$DEV" |awk -F: '{ print $3 }')
		done
	fi
	echo "$FILENAME $(debugfs -R 'stat <'`stat --print=%i $FILENAME`'>' $DEVICE 2>/dev/null \
		|grep ^crtime |awk '{ print $4,$5,$6,$7,$8 }')"
done

