#!/bin/bash

case $1 in
1)
	sha1sum $2 | awk '{ print $1 }'
	;;
224)
	sha224sum $2 | awk '{ print $1 }'
	;;
256)
	sha256sum $2 | awk '{ print $1 }'
	;;
384)
	sha384sum $2 | awk '{ print $1 }'
	;;
512)
	sha512sum $2 | awk '{ print $1 }'
	;;
*)
	echo "Usage: $(basename $0) { 1 | 224 | 256 | 384 | 512 } FILENAME"
	exit 1
	;;
esac

